cmake_minimum_required(VERSION 3.25)
project(ksp_opt LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
if(NOT CMAKE_CXX_COMPILER)
    set(CMAKE_C_COMPILER clang)
    set(CMAKE_CXX_COMPILER clang++)
endif()
add_compile_options(-Wall -O3 -march=native)
add_subdirectory(precision)
add_subdirectory(newton)
add_subdirectory(runge_kutta)
add_subdirectory(parallel)
add_subdirectory(auto_diff)
add_subdirectory(yoshida)

if(PROJECT_IS_TOP_LEVEL)
     include(CTest)
     add_subdirectory(tests)
     add_subdirectory(examples)
endif()
