cmake_minimum_required(VERSION 3.25)
project(ksp_opt LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
if(NOT CMAKE_CXX_COMPILER)
    set(CMAKE_C_COMPILER clang)
    set(CMAKE_CXX_COMPILER clang++)
endif()
add_compile_options(-Wall -O3 -march=native)
add_subdirectory(precision)
add_subdirectory(newton)
add_subdirectory(runge_kutta)
add_subdirectory(parallel)
add_subdirectory(auto_diff)

if(POLICY CMP0167)
  cmake_policy(SET CMP0167 NEW)
endif()

find_package(Boost REQUIRED)
find_package(fmt REQUIRED)
add_executable(ksp_opt src/main.cpp)
target_include_directories(ksp_opt PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(ksp_opt Boost::headers auto_diff precision parallel newton runge_kutta mpfr gmp fmt::fmt)
file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/plot_scr
     DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
 if(PROJECT_IS_TOP_LEVEL)
     include(CTest)
     add_subdirectory(tests)
endif()
